trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |        
        npm install 
        npm run build
    env:
      REACT_APP_ISS: $(REACT_APP_ISS)
      REACT_APP_ISS_CLIENT_ID: $(REACT_APP_ISS_CLIENT_ID)
      
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'build'
      api_location: ''
      output_location: ''
      skip_app_build: false
      azure_static_web_apps_api_token:  ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_OCEAN_078742610 }}

    - bash: echo $(REACT_APP_ISS)
    - bash: echo $(REACT_APP_ISS_CLIENT_ID)